# Site settings
title: Beyond Excel Biology
markdown: kramdown
description: "A blog about biology, data analysis, and the tools that bridge them"
url: "https://beyond-excel-biology.com"
baseurl: ""
author: "Simeon"
excerpt_separator: "<!--more-->"

# Build settings
plugins:
  - jekyll-feed

# Feed settings
feed:
  posts_limit: 20
  excerpt_only: false

# Exclude files and directories from processing
exclude:
  - devlog.md
  - Gemfile
  - Gemfile.lock
  - .git
  - .github
  - README.md
  - vendor
  - .bundle
  - "[!_]*.md"
  - "*.txt"
  - unused_pages
  - personal_blog_templates

# Default layouts
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      layout: blogpost
